#!/usr/bin/python
import BeautifulSoup
import newurllib2
Soup = BeautifulSoup.BeautifulSoup
response = newurllib2.urlopen('http://www.nfl.com/teams/pittsburghsteelers/schedule?team=PIT').read()
soup = Soup(response)
#print(soup.prettify())

ranking = soup.find("p", attrs={"class": "team-overall-ranking"}).contents
rankstr = str(ranking)
foo, rank, record = rankstr.split("'")
foo, rec, bar = record.split("<")#
foo, newrec = rec.split(">")


response = newurllib2.urlopen('http://www.nfl.com/schedules/2015/REG/STEELERS').read()
soup = Soup(response)
#print(soup.prettify())

next = soup.find("li", attrs={"class": "schedules-list-matchup pre expandable primetime type-reg expanded no-weather"}).contents
newsoup = Soup(str(next))
print newsoup
date = str(newsoup.find("span", attrs={"class": "date"}).contents)
foo, date, bar = date.split("'")
time = str(newsoup.find("span", attrs={"class": "time"}).contents)
foo, time, bar = time.split("'")
at = str(newsoup.find("span", attrs={"class": "at "}).contents)
foo, at, bar = at.split("'")
vs = str(newsoup.find("span", attrs={"class": "team-name home "}).contents)
foo, vs, bar = vs.split("'")


print("Steelers: %s%s" % (rank, newrec)),
print(" Next game: %s %s %s %s" % (date, time, at, vs))

